server:
  port: 9527

spring:
  application:
    name: cloud-gateway  # 以微服务注册进consul或nacos服务列表内

  cloud:
    consul: # 配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: pay_routh1  # pay_routh1      # 路由的ID（类似mysql主键ID），没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8848        # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service        # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**      # 断言，路径相匹配的进行路由
#            - After=2024-03-05T08:50:49.807618300+08:00[Asia/Shanghai]  # 超过规定时间可以访问
#            - Between=2024-03-05T08:50:49.807618300+08:00[Asia/Shanghai],2024-03-05T09:50:49.807618300+08:00[Asia/Shanghai]  # 在时间段内可以访问
#            - Cookie=username,zzyy  # Cookie Route Predicate需要两个参数，一个是 Cookie name ,一个是正则表达式。路由规则会通过获取对应的 Cookie name 值和正则表达式去匹配，如果匹配上就会执行路由，如果没有匹配上则不执行
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.fuswx.com
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
#            - RemoteAddr=192.168.1.1/24  # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - Method=GET  # 配置某个请求地址，只能用GET/POST方法访问，方法限制
#            - My=diamond
#            - name: My
#              args:
#                userType: diamond

        - id: pay_routh2  # pay_routh2      # 路由的ID（类似mysql主键ID），没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8848        # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service        # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**
#            - Before=2024-03-05T08:50:49.807618300+08:00[Asia/Shanghai]  # 超过规定时间不可访问

        - id: pay_routh3 # pay_routh3
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**  # 断言，路径相匹配的进行路由,默认正确地址
#            - Path=/gateway/filter/**  # 断言，为配合PrefixPath测试过滤，暂时注释掉/pay
#            - Path=/XYZ/abc/{segment}  # 断言，为配合PrefixPath测试过滤，暂时注释掉/pay
          filters:
            - My=abcd
#            - RedirectTo=302, https://www.baidu.com/  # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.baidu.com/
#            - SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致
#            - PrefixPath=/pay  # http://localhost:9527/pay/gateway/filter 被拆分为：PrefixPath + Path
#            - AddRequestHeader=X-Request-fuswx1,fuswxValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-fuswx2,fuswxValue2
#            - RemoveRequestHeader=sec-fetch-site  # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,Blue-updateByYzc  # 将请求头src-fetch-mode对应的值修改为Blue-updateByYzc
#            - AddRequestParameter=customerId,1314521  # 新增请求参数Parameter：k,v
#            - RemoveRequestParameter=customerName  # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-fuswx,BlueResponse  # 新增回应头：k,v
#            - SetResponseHeader=Date,2099-11-11  # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type  # 将默认自带Content-Type回应属性删除
#      default-filters:  # 配置在此处相当于全局通用，自定义秒变Global
#        -